# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'react-native-vs-cocoa' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'

  # Pods for react-native-vs-cocoa

  target 'react-native-vs-cocoaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
